### ISSUE TITLE
ASCII equals sign is blank

### ISSUE THREAD

**Issue by laarmen** [steinbergmedia/bravura#1]
Hi!

While all the ASCII characters are left unimplemented in the font, which is quite nice, it appears the "=" sign isn't, and, worse, it is implemented as a blank space. Is there a reason behind it?

Cheers,
Simon

**Comment by dspreadbury** [comment]
A handful of glyphs in the ASCII range are defined as spacing characters of various widths, more usefully for the Bravura Text font rather than for Bravura itself. As it says in the [Bravura Text docs](https://github.com/steinbergmedia/bravura/blob/master/redist/bravura-text.md):

"In order to insert space between symbols, use the following keys:

Typing `Space` advances the input position by half a space.
Typing `-` (hyphen) advances the input position by one space.
Typing `=` (equals) advances the input position by two spaces."

This is as intended for the time being. If you have a counter-proposal for another way to handle this, please feel free to reopen this issue to suggest it.

**Comment by laarmen** [comment]
Thanks for the info. I got bitten by it when trying to write metronome info
on a system that uses a backup font when the main doesn't provide the
symbol, hence my surprise, and my google-fu didn't seem to be good enough
to turn up the right info.

In any case, thanks for the fonts, it is amazing work!
