### ISSUE TITLE
Bravura-Fingerings font

### ISSUE THREAD

**Issue by lasconic** [steinbergmedia/bravura#2]
There used to be several hundreds fingering code points in both SMuFL and Bravura. I wonder if there's any plan to release a font with just these symbols?

**Comment by dspreadbury** [comment]
It's certainly a possibility. The fingering charts basically worked but they were somewhat fiddly to put together. I don't have any time to look into this right now, but I will try to find some time to look into it soon.

**Comment by lasconic** [comment]
I took an old Bravura and removed all glyphs but the fingerings. Here is the result.

[BravuraFingering.otf.zip](https://github.com/steinbergmedia/bravura/files/484696/BravuraFingering.otf.zip)

A MuseScore user proposed to take a look to make a recorder plugin, so basically associate notes with a string of glyphs from this font.

**Comment by eduardomourar** [comment]
@lasconic and @dspreadbury I know this is closed and pretty old, but I was wondering if this additional font has a repo or name? If not, I would pick up this myself if you guys don't mind. I say this because I already created a [flute fingering chart plugin](https://github.com/eduardomourar/flute-fingering) for MuseScore and made a font (that in the end can be replaced by this). BTW I nice name to this font would be _fiati_ (wind instruments in Italian).

**Comment by dspreadbury** [comment]
Here is a zip file containing a FontLab 5 and a UFO version of the glyphs that were removed several years ago, in case it's helpful to you. There's no repository for it as far as I know, but please feel free to set one up.

[fingering-glyphs.zip](https://github.com/steinbergmedia/bravura/files/3693649/fingering-glyphs.zip)

**Comment by eduardomourar** [comment]
Repository created https://github.com/eduardomourar/fiati and I will start to make the changes needed for Flute and Recorder. Thank you very much!
