### ISSUE TITLE
Add glyphs to Olympian and Magrathean Sagittal accidental extension ranges

### ISSUE THREAD

**Issue by dspreadbury** [steinbergmedia/bravura#39]
Per w3c/smufl#156 we now need to add these new glyphs to Bravura. Douglas Blumeyer (@cmloegcmluin) has provided a version of the Bravura OTF file with the new accidentals added. These need to be merged into the master version of the font.

**Comment by cmloegcmluin** [comment]
@dspreadbury  — Hopefully we are not too late and this will amount to no inconvenience. Could we request that you source from the further updated version of the Bravura font attached here (zipped .otf: [BravuraSagittalUpdate_v11.zip](https://github.com/steinbergmedia/bravura/files/5638425/BravuraSagittalUpdate_v11.zip)) when you merge these new glyphs into master? 

After running FontForge's validation tests, we caught (and fixed) a couple subtle problems with the new glyphs we designed:

- The (clockwise vs. anticlockwise) directions were wrong for the downward versions of all of our new glyphs.
- Several of our new glyphs were missing points at extrema. 

I know the last MNCC meeting of the year is less than a week from now, so I completely understand if this comes too late and you have your hands full already.

**Comment by dspreadbury** [comment]
Fixed in 301087c.

**Comment by cmloegcmluin** [comment]
@dspreadbury I've just noticed something that's off in the latest `bravura_metadata.json`. Somehow the widths for some glyphs have gotten switched: those for 1 **t**ina (with a 't') glyphs and 2 **m**ina (with an 'm').

You can tell something is wrong with the 2 mina glyphs because they should be the same as the 6 tina glyphs (1 mina = 3 tinas). And I noticed that the 1 tina glyph had way too much space on its right side, and it's the same value as the 2 mina should be. And if you take what the 2 mina is now and give that to the 1 tina, the 1 tina looks right. 

I checked in the BravuraSagittalUpdate_v11.zip I sent (and it appears you used) above and the widths seem fine there. So perhaps something has gone wrong in whatever script generates `bravura_metadata.json`?

```json
		"accSagittal1TinaDown":1.12,
		"accSagittal1TinaUp":1.12,
...
		"accSagittal2MinasDown":0.62,
		"accSagittal2MinasUp":0.62,
...
		"accSagittal6TinasDown":1.12,
		"accSagittal6TinasUp":1.12,
```

should be: 

```json
		"accSagittal1TinaDown":0.62,
		"accSagittal1TinaUp":0.62,
...
		"accSagittal2MinasDown":1.12,
		"accSagittal2MinasUp":1.12,
...
		"accSagittal6TinasDown":1.12,
		"accSagittal6TinasUp":1.12,
```

That's in the `glyphAdvanceWidths` part of the data, which I understand is relatively new, but we should see a parallel set of changes to the `glyphBBoxes` data I'd think. It's just the x-coordinate of the `bBoxNE` that's off. Maybe it's just a typo or something, because it's off by 0.5, a single digit. `accSagittal2MinasDown` and `accSagittal2MinasUp` should be 0.**8**72, not 0.**3**72, and the other way around for `accSagittal1TinaDown` and `accSagittal1TinaUp`.

Please let me know if there's anything else I can do to help or clarify. Thanks as always for your help.

**Comment by dspreadbury** [comment]
It seems most likely that I've transposed the glyphs themselves, rather than the metadata being off.

accSagittal2MinasUp U+E3F6  
accSagittal2MinasDown U+E3F7  
accSagittal1TinaUp U+E3F8  
accSagittal1TinaDown U+E3F9

[https://blog.dorico.com/wp-content/uploads/mina-tina-miney-mo.png](https://blog.dorico.com/wp-content/uploads/mina-tina-miney-mo.png)

Perhaps you can confirm whether I've got the glyphs in the correct order?

**Comment by cmloegcmluin** [comment]
I confirm that these codepoint labels you just wrote in your last post, and that appear in its linked image, are all correct. 

I like your name for the image 😄

**Comment by dspreadbury** [comment]
OK, I've found the error, which is that the glyph name metadata in the FontLab source for Bravura is transposed for U+E3F6/U+E3F8 and U+E3F7/U+E3F9. Thanks for spotting it. Next time the font and its metadata is regenerated, this error will be eliminated.

**Comment by cmloegcmluin** [comment]
Ah ha! Okay, that's good news. Thanks Daniel.
