### ISSUE TITLE
How to install and use on Windows 10 and the Web

### ISSUE THREAD

**Issue by iam1me** [steinbergmedia/bravura#54]
Hi,

I'm considering developing an application for editing music notation and was interested in using the Bravura font for this. I'm having trouble finding clear instructions on how to go about installing and using this font both for Windows 10 and for the web. It'd be nice if this info were in the primary README file this project. Please advise - Thanks :)

**Comment by dspreadbury** [comment]
Sorry for not coming back to you sooner, Ryan.

You are free to redistribute the font software yourself, so that you can include it in the distribution for your Windows application. Most installer-building software provides special support for installing fonts. At its simplest, you just need to make sure that the OTF file gets installed to the Windows\\Fonts folder, but these days on Windows fonts are often installed in a user-specific location, so it's best to use the dedicated support for font installation of your installer builder.

On the web, it's normally sufficient to choose which web version of the font you want to use – WOFF2 is probably the most commonly-used web font format these days – and put it on your server, then reference it in the CSS file you use. [Check out this introduction from MDN.](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts)
