### ISSUE TITLE
Whole rest is on wrong staff line

### ISSUE THREAD

**Issue by ewanmellor** [steinbergmedia/bravura#8]
The whole-rest glyph has the metrics set so that it hangs from the third line on the staff.  This is incorrect according to Wikipedia https://en.wikipedia.org/wiki/Rest_(music).  It should hang from the second line on the staff.

This is in Bravura (as opposed to Bravura Text).

Note that the long, breve, and minim rests are correctly positioned (center two spaces, second space, and resting on the third line respectively) so I know that my rendering is set up correctly in general.

This was noted in a forum post in 2015 (https://forum.makemusic.com/default.aspx?f=6&m=453271) saying "the default position of the whole note rest is lower than Finale expects".

<img width="229" alt="screen shot 2019-01-25 at 2 03 20 pm" src="https://user-images.githubusercontent.com/894011/51775316-2a6fa600-20aa-11e9-938b-463a57629716.png">

**Comment by dspreadbury** [comment]
The positioning of the whole rest is correct: the rest glyphs are registered assuming that y = 0 is a staff line, but not necessarily the middle staff line. I think that probably this should be clariied in the SMuFL specification, so I have opened an issue (w3c/smufl#100) to do that.

**Comment by eguneys** [comment]
I use 
This is the text I insert into webpage: `''`

namely: `U+E4E3 U+E4E4 U+E4E5`
or seen here: https://w3c.github.io/smufl/latest/tables/rests.html :

`restWhole restHalf restQuarter`

a `Whole rest, Half rest and Quarter rest`.

It shows as in this image:

[![music rests][1]][1]

As you can see, it is wrong, because it actually shows a `Half rest, Whole rest, Quarter rest`.

If I switch the half rest and whole rest it works as expected. So by any chance these two glyphs are actually switched up wrongly?

  [1]: https://i.stack.imgur.com/KD4WW.png

**Comment by eguneys** [comment]
The previous image shows rests positioned on c5 which is not a staff line, so I thought b4 would work, now it renders as this image:

![image](https://user-images.githubusercontent.com/3844764/156460935-d2cd4f6e-a749-4f34-ac6a-8a5d3963355b.png)

The issue here is the same as the OP's.

I don't want to add superfluous code to fix this in my code, just make it right.

**Comment by Jojo-Schmitz** [comment]
MuseScore certainly does not do any special casing for Bravura in this respect.
